---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - TZ=America/Los_Angeles

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive --pure-lockfile

jobs:
  include:
    - stage: test
      name: "Linting and tests"
      script: yarn lint:js
      script: yarn test
#    - stage: production
#      name: "Deploy to production"
#      script: node_modules/.bin/ember deploy production --activate=true
